apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrate
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      containers:
      - name: "{{ .Chart.Name }}-migrate"
        image: "{{ include "kab-helm.image" . }}"
        args: ["migrate"]
        env:
          - name: DB_VENDOR
            value: "postgres"
          - name: DATABASE_NAME
            valueFrom: { secretKeyRef: { name: kab-pguser-kab, key: dbname } }
          - name: DATABASE_USER
            valueFrom: { secretKeyRef: { name: kab-pguser-kab, key: user } }
          - name: DATABASE_PASSWORD
            valueFrom: { secretKeyRef: { name: kab-pguser-kab, key: password } }
          - name: DATABASE_HOST
            valueFrom: { secretKeyRef: { name: kab-pguser-kab, key: host } }
          - name: DATABASE_PORT
            valueFrom: { secretKeyRef: { name: kab-pguser-kab, key: port } }
      restartPolicy: Never
  backoffLimit: 4