kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: kab-test
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'kab-test:latest'
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'python:3.9-ubi9'
      dockerfilePath: Containerfile
  source:
    type: Git
    git:
      uri: 'https://github.com/d-kaylor/django-test'
  runPolicy: Serial