# Generated by Django 4.1.7 on 2023-03-24 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test2',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
