# Generated by Django 4.1.7 on 2023-03-24 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0002_test_test2'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test3',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
